version: '3'
services:
  node-app:
    build: .
    ports:
      - '3010:3010'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - APP_NAME=mainstack-backend-interview-app
      - APP_PORT=3010
      - APP_ENV=development
      - DATABASE_URL=mongodb://test:user@mongo-db:27017/mainstack-app?authSource=admin
      - JWT_SECRET=secret
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=user
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
