version: '3'
services:
  node-app:
    build: .
    ports:
      - '3010:3010'
    volumes:
      - .:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - .env
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=user
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
